service: cru-udp-aa-sync
frameworkVersion: '3'
configValidationMode: error
plugins:
  - serverless-webpack

provider:
  name: aws
  stage: ${env:ENVIRONMENT}
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-888294ed
    subnetIds:
      - subnet-f2c2dfda # us-east-1a
      - subnet-1508db62 # us-east-1b
      - subnet-3fd94266 # us-east-1c
  stackTags:
    Name: ${env:PROJECT_NAME}-${self:custom.environmentMap.${env:ENVIRONMENT}}
    owner: udp-support@cru.org
    application: ${env:PROJECT_NAME}
    env: ${self:custom.environmentMap.${env:ENVIRONMENT}}
    managed_by: serverless-framework
    function: lambda
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - S3:ListBucket
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - ${env:S3_ECID_BUCKET}
        - Effect: Allow
          Action:
            - S3:GetObject
            - S3:PutObject
            - S3:DeleteObject
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - ${env:S3_ECID_BUCKET}
                - '/*'
  layers:
    - arn:aws:lambda:us-east-1:072686360478:layer:node-16_14_2:1
  environment: ${file(env.js)}

package:
  individually: true
  patterns:
    - '!.webpack/**'
    - '!test/**'
    - '!**/*.test.js'
    - '!.deployment/**'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
    excludeFiles: '**/*.test.js'
    excludeRegex: \.ts|test|\.map
  environmentMap:
    production: prod
    staging: stage
    development: dev
    lab: lab

functions:
  aa-sync:
    handler: handlers/aa-sync.handler
    timeout: 120
    events:
      - schedule: rate(12 hours)
